server:
  port: 7777
#spring:
#  mvc:
#    static-path-pattern: /res/**

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myhr
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver      #com.mysql.cj.jdbc.Driver要不然你们一旦写出
    #druid配置
    druid:
      aop-patterns: com.icss.boot.*   #监控这个包下的所有Bean
      filters: stat,wall   #开启监控页面 和 防火墙
      stat-view-servlet:   #监控sql页面
        enabled: true      #设置可用
        login-username: admin  #Druid监控页面账号密码
        login-password: admin
        reset-enable: true    #设置重置按钮是否有效
      web-stat-filter:  #监控web应用
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.jpg,*.png,*.gif,*.css,*.ico,/druid/' #不监控的内容
      filter:
        stat:
          slow-sql-millis: 1000 #超过1000毫秒 会被认为是一次慢查询
          logSlowSql: true
          enabled: true
      wall:
        enabled: true
        config:
          drop-table-allow: false  #防火墙  禁止删表
mybatis:
  configuration:
    map-underscore-to-camel-case: true #设置列名直接自动转小驼峰写法
  type-aliases-package: com.icss.hr.*.pojo #自动设置别名 该包中的所有类的类名设置为别名
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
